Dockerizing
TeamProductionSystem/Momentors_Backend pull request #158
Opened 2023-10-12 15:55 UTC by jimbandrews

## **Pull Request Template**

### **1. Targeted Issue** ###

*(The first step to a good solution is knowing the problem. Please link the issue here.)*

Issue #... or
Ticket #...

https://trello.com/c/RBwhtEEA/69-implement-docker-be

### **2. Overview of Solution** ###

*(You've put in the hard work, now's your chance to tell us about it. What's your solution in a nutshell?)*

The entire backend (api, redis, and celery servers, database) can be run locally inside docker containers. This requires Docker and Docker Desktop to be installed, and simplifies running it locally to a single terminal window and (at most) 3 commands. 

### **3. Tools Used** ###

*(Share the tools, libraries, or techniques you've used in your solution.)*

Docker, Docker Compose

### **4. Testing Strategy** ###

*(No code is complete without tests. Outline what you've tested and how.)*

Follow the new instructions I added in the README for setup and teardown.

I've spun up the containers and used Postman/Insomnia to access the API endpoints. I've also connected to the database container via Postico 2.

### **5. Future Implications** ###

*(Let's anticipate potential effects of your changes. Are there any potential issues down the line?)*

Contributors will need to update their environment variables for the database connection. I had to change this to make it easier for connecting the api and celery containers to the database.

This will give new contributors a chance to familiarize themselves with Docker, which is a necessary technology in today's industry. It will also simplify setup, leading to less confusion when starting development.

### **6. Screenshots** ###

*(A picture is worth a thousand words. Include screenshots of your changes if relevant.)*

### **7. Code Reviewers** ###

*(Who else is in the loop? Mention your team or other contributors here.)*

Peri Sparr, Laura Andrews, and Christina Conley all participated in group meetings to setup and debug this feature.

---

Before you go...

- [x ]  I have linked the relevant issue
- [x ]  I have provided an overview of my solution
- [x ]  I have shared the tools I've used
- [x ]  I have outlined my testing strategy
- [x ]  I have considered future implications of my changes
- [x ]  I have included relevant screenshots
- [x ]  I have kept my team in the loop

---

### Big high-fives for your incredible pull request! We're thrilled to have you as a contributor! Our team will dig into your proposed changes and give you some feedback or merge them if they're good to go. Your contributions mean the world to us!    
![Screenshot 2023-10-12 at 11 48 36 AM](https://github.com/TeamProductionSystem/Momentors_Backend/assets/8958872/eb1d58cb-0660-4c02-a686-dfe36aea61c5)
![Screenshot 2023-10-12 at 11 48 56 AM](https://github.com/TeamProductionSystem/Momentors_Backend/assets/8958872/9b32f65b-7661-46da-b041-89ecda215531)
![Screenshot 2023-10-12 at 11 49 16 AM](https://github.com/TeamProductionSystem/Momentors_Backend/assets/8958872/a83d1764-9614-43c8-9cee-5e21b11f1ae3)
![Screenshot 2023-10-12 at 11 49 42 AM](https://github.com/TeamProductionSystem/Momentors_Backend/assets/8958872/eb82ef93-7c26-49e4-84e5-83ae68d76fc3)

2023-10-12 20:08 UTC, esparr requested changes
Very excited to have docker set up. LETS GOOOO

2023-10-12 22:15 UTC, jimbandrews commented on team_production_system/serializers.py
File removed

2023-10-12 22:15 UTC, jimbandrews commented on team_production_system/urls.py
Changes were to make code more legible

2023-10-12 22:15 UTC, jimbandrews commented on team_production_system/views.py
File removed

2023-10-12 22:15 UTC, jimbandrews commented on config/settings.py
> +    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
Line deleted

2023-10-12 22:15 UTC, jimbandrews commented on config/settings.py
> +    'drf_spectacular',
Line deleted

2023-10-13 15:32 UTC, esparr approved these changes
Very excited to have docker set up. LETS GOOOO

2023-10-13 15:49 UTC, merged